export interface CloudConfig {
  mode: 'cloud'
  projectKey: string
  supabaseUrl: string
  supabaseAnonKey: string
}

export interface LocalConfig {
  mode: 'local'
  port: number
  dataFile: string
}

export type MCPConfig = CloudConfig | LocalConfig

export class ConfigError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'ConfigError'
  }
}

function require_(env: NodeJS.ProcessEnv, key: string): string {
  const v = env[key]
  if (!v || v.trim() === '') {
    throw new ConfigError(`Missing required env var: ${key}`)
  }
  return v
}

const DEFAULT_PORT = 1817
const DEFAULT_DATA_FILE = '.remarq/annotations.json'

export function parseEnv(env: NodeJS.ProcessEnv): MCPConfig {
  const cloudRequested = Boolean(
    env.REMARQ_PROJECT_KEY || env.REMARQ_SUPABASE_URL || env.REMARQ_SUPABASE_ANON_KEY,
  )

  if (cloudRequested) {
    const projectKey = require_(env, 'REMARQ_PROJECT_KEY')
    const supabaseUrl = require_(env, 'REMARQ_SUPABASE_URL')
    const supabaseAnonKey = require_(env, 'REMARQ_SUPABASE_ANON_KEY')

    if (!projectKey.startsWith('pk_')) {
      throw new ConfigError('REMARQ_PROJECT_KEY must start with `pk_` (generated by `npx @web-remarq/cloud gen-key`)')
    }
    if (!supabaseUrl.startsWith('https://')) {
      throw new ConfigError('REMARQ_SUPABASE_URL must start with https://')
    }

    return { mode: 'cloud', projectKey, supabaseUrl, supabaseAnonKey }
  }

  const rawPort = env.REMARQ_PORT ?? String(DEFAULT_PORT)
  const port = Number(rawPort)
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    throw new ConfigError(`REMARQ_PORT must be an integer between 1 and 65535, got "${rawPort}"`)
  }

  return { mode: 'local', port, dataFile: env.REMARQ_DATA_FILE ?? DEFAULT_DATA_FILE }
}
