export interface MCPConfig {
  projectKey: string
  supabaseUrl: string
  supabaseAnonKey: string
}

export class ConfigError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'ConfigError'
  }
}

function require_(env: NodeJS.ProcessEnv, key: string): string {
  const v = env[key]
  if (!v || v.trim() === '') {
    throw new ConfigError(`Missing required env var: ${key}`)
  }
  return v
}

export function parseEnv(env: NodeJS.ProcessEnv): MCPConfig {
  const projectKey = require_(env, 'REMARQ_PROJECT_KEY')
  const supabaseUrl = require_(env, 'REMARQ_SUPABASE_URL')
  const supabaseAnonKey = require_(env, 'REMARQ_SUPABASE_ANON_KEY')

  if (!projectKey.startsWith('pk_')) {
    throw new ConfigError('REMARQ_PROJECT_KEY must start with `pk_` (generated by `npx @web-remarq/cloud gen-key`)')
  }
  if (!supabaseUrl.startsWith('https://')) {
    throw new ConfigError('REMARQ_SUPABASE_URL must start with https://')
  }

  return { projectKey, supabaseUrl, supabaseAnonKey }
}
